### ISSUE TITLE
大佬可以添加代码覆盖率的 badge 吗？

### ISSUE THREAD

**Issue by aQuaYi** [nntaoli-project/GoEx#122]
虽然，100% 的代码覆盖率也说明不了什么。
但是，没有覆盖率的代码也容易出现隐患。
希望可以添加代码覆盖率的 badge。

**Comment by xiandong79** [comment]
@aQuaYi 你也在goex 微信开发群吗？

**Comment by aQuaYi** [comment]
@xiandong79 不在呀，请问怎么加入呢？

**Comment by xiandong79** [comment]
qi839395901 是我的微信。

**Comment by aQuaYi** [comment]
@xiandong79  已加，可以删除微信号了

**Comment by nntaoli** [comment]
感谢提意见，由于交易所API的特殊性，这方面做起来会一定的复杂性，不过目前也正在积极做相关的测试。
