### ISSUE TITLE
每个交易所的 API 都会进行限速，GoEx 是如何处理交易所限速的？

### ISSUE THREAD

**Issue by aQuaYi** [nntaoli-project/GoEx#123]
在 GoEx 的代码里面，我搜索了 `rate` , `limit` 和 `limiter`  ，都没有找到相关的代码。所以，我暂且认为 GoEx 没有进行相关的处理工作。
个人觉得，交易所 API 有必要集成限速功能。理由如下：

1. 超出限制后，交易所会返回错误码。以 binance 为例，达到限制返回 `429`，超过限制返回 `418`。不对相关错误码进行处理的 API 不是完整的 API。
1. 交易所 API 模块可以设计成单例模式，进行全局管理。

**Comment by nntaoli** [comment]
库目前没对limit做处理，这个应该是有策略自己做最好吧，库怎么做？没办法处理吧。
单例模式不适合吧，比如okex，我可能需要同时new多个账号的实例。
