### ISSUE TITLE
支持兼容 https://github.com/valyala/fasthttp

### ISSUE THREAD

**Issue by nntaoli** [nntaoli-project/GoEx#127]

**Comment by beaquant** [comment]
and [https://github.com/fasthttp/websocket](https://github.com/fasthttp/websocket)

**Comment by nntaoli** [comment]
![fasthttp_bench2](https://user-images.githubusercontent.com/19357247/68921253-10c35a80-07b3-11ea-852a-e29ab9d7a147.png)
经过bench性能测试，发生fasthttp 作为httpclient的速度并不比http库快，这个future可能会被关闭。
