### ISSUE TITLE
是不是这里加一个开关控制是否使用aws比较好呢？

### ISSUE THREAD

**Issue by cmdedj** [nntaoli-project/GoEx#129]
REST API

https://api.huobi.pro

https://api-aws.huobi.pro

Websocket Feed（行情）

wss://api.huobi.pro/ws

wss://api-aws.huobi.pro/ws

Websocket Feed（资产和订单）

wss://api.huobi.pro/ws/v1

wss://api-aws.huobi.pro/ws/v1

**Comment by nntaoli** [comment]
#128

**Comment by cmdedj** [comment]
还有看了下huobi的ws只有合约交易的，没有现货交易的

**Comment by nntaoli** [comment]
是的

**Comment by cmdedj** [comment]
以后打算支持吗

**Comment by nntaoli** [comment]
会支持的，ws api还在规范中，后面这部分可能会有一些改动

**Comment by cmdedj** [comment]
> 会支持的，ws api还在规范中，后面这部分可能会有一些改动

我看现货这里还有账户资产这方面会支持吗，现在要开发这块的内容，只能强撸了TAT

**Comment by nntaoli** [comment]
```golang
huobiApi := NewAPIBuilder().Endpoint("https://api-aws.huobi.pro").APIKey("").APISecretkey("").Build(goex.HUOBI_PRO)
```
