### ISSUE TITLE
futuresEndPoint为空的情况需加以提示

### ISSUE THREAD

**Issue by beaquant** [nntaoli-project/GoEx#136]
这些地方可否先判断是否设置了futuresEndPoint，如果是空，给提示panic

https://github.com/nntaoli-project/GoEx/blob/bd3235e139b85955640fe34290bfcb62a56281bc/builder/APIBuilder.go#L263

**Comment by nntaoli** [comment]
不需要提示，可以不设置endpoint的

**Comment by beaquant** [comment]
不设置也没默认值呀
