### ISSUE TITLE
可以增加对库币KuCoin的支持吗？

### ISSUE THREAD

**Issue by niulingyun** [nntaoli-project/GoEx#138]
库币还是比较知名的交易所，深度也不错，我在那边有手续费返利。
https://docs.kucoin.com/  文档在这儿。谢谢。

**Comment by nntaoli** [comment]
指定添加特定交易所，可能需要发布一点开发奖励，开源项目请理解，可加QQ：574829125

**Comment by niulingyun** [comment]
> 指定添加特定交易所，可能需要发布一点开发奖励，开源项目请理解，可加QQ群：574829125

群主拒绝添加任何成员。

**Comment by nntaoli** [comment]
> > 指定添加特定交易所，可能需要发布一点开发奖励，开源项目请理解，可加QQ群：574829125
> 
> 群主拒绝添加任何成员。

不会吧，再试试。他们都可以加入的。

**Comment by nntaoli** [comment]
> 库币还是比较知名的交易所，深度也不错，我在那边有手续费返利。
> https://docs.kucoin.com/ 文档在这儿。谢谢。

加我私人QQ:2767415655
