### ISSUE TITLE
okex v3 公共行情频道ws 什么时候加一下呢 

### ISSUE THREAD

**Issue by mote0302** [nntaoli-project/goex#146]
future ws v3 都写好了 getTablePrefix加上 现货频道就好了  
想通过okexspotws 走v3接口 可以自己组合请求参数 但是卡在了 connectWs上

**Comment by nntaoli** [comment]
https://github.com/nntaoli-project/GoEx/blob/dev/okcoin/OKEx_V3_Future_Ws.go  你看下这个

**Comment by mote0302** [comment]
看了 订阅只有期货没有现货 即只有swap和future 没有spot啊

**Comment by milescui** [comment]
需要spot v3 ws功能，希望作者能添加。感谢

**Comment by nntaoli** [comment]
okex futures v3 ws功能已添加，这几天会集中把ws api完善下。

**Comment by milescui** [comment]
非常感谢，辛苦啦
