### ISSUE TITLE
能不能加一下成交订单更多的信息

### ISSUE THREAD

**Issue by ballyang** [nntaoli-project/goex#150]
能不能加一下成交订单更多的信息
比如okex的账单,即包含了当前这个订单成交后,一个缀合哪些订单,手续费是多少等的信息
比如binance的成交订单里,能查到指定订单的成交信息,如手续费之类的

**Comment by nntaoli** [comment]
你是说增加一个接口吗？

**Comment by milescui** [comment]
建议参考ccxt的实现，在所有返回的数据类型中，都包含一个 info字段，用于存储交易所返回的原始信息

**Comment by nntaoli** [comment]
@milescui 谢谢建议，好的
