### ISSUE TITLE
请问这.......

### ISSUE THREAD

**Issue by gzw13999** [nntaoli-project/goex#157]
刚go get的，没做任务更改。
# github.com/nntaoli-project/goex/kucoin
..\github.com\nntaoli-project\goex\kucoin\kucoin.go:105:37: cannot use params (type map[string]string) as type *kucoin.CreateOrderModel in argument to kc.service.CreateOrder
..\github.com\nntaoli-project\goex\kucoin\kucoin.go:135:37: cannot use params (type map[string]string) as type *kucoin.CreateOrderModel in argument to kc.service.CreateOrder
..\github.com\nntaoli-project\goex\kucoin\kucoin.go:165:37: cannot use params (type map[string]string) as type *kucoin.CreateOrderModel in argument to kc.service.CreateOrder
..\github.com\nntaoli-project\goex\kucoin\kucoin.go:195:37: cannot use params (type map[string]string) as type *kucoin.CreateOrderModel in argument to kc.service.CreateOrder
错误: 进程退出代码 2.

**Comment by niulingyun** [comment]
https://github.com/nntaoli-project/goex/pull/158/files

**Comment by nntaoli** [comment]
fixed #158
