### ISSUE TITLE
any easy example to get latest price of exchange for example ?

### ISSUE THREAD

**Issue by bcashier** [nntaoli-project/goex#173]
Hi,

Is there any examples for this aweose lib please ?

Thank you !

**Comment by nntaoli** [comment]
reference: https://github.com/nntaoli-project/download_binance_kline_history/blob/master/main.go

**Comment by nntaoli** [comment]
https://github.com/nntaoli-project/goex/wiki

**Comment by bcashier** [comment]
@nntaoli Thank you sir !
