### ISSUE TITLE
请问有支持btcc的 打算吗

### ISSUE THREAD

**Issue by jxc6698** [nntaoli-project/GoEx#18]
请问有支持btcc的打算吗

**Comment by nntaoli** [comment]
最近可能我没时间，等闲下来的时候，可以添加。
同时如果您有时间，欢迎贡献代码！

**Comment by jxc6698** [comment]
哦哦，我试试，btcc好像没有restful API了。必须要用fix 来发送交易请求

**Comment by nntaoli** [comment]
有restful api吧
https://www.btcc.com/apidocs

**Comment by nntaoli** [comment]
已支持btcchina.com
