### ISSUE TITLE
Okex V5 exchange integration

### ISSUE THREAD

**Issue by pavhov** [nntaoli-project/goex#194]

**Comment by theWayToAI** [comment]
It will be great if support okex v5 !

**Comment by soyoeml** [comment]
+1

**Comment by panxianhai** [comment]
有支持V5的打算吗

**Comment by conbanwa** [comment]
It will be great if support okex v5 !

**Comment by renat1015** [comment]
when will be added okex V5 WS?

**Comment by Durden-T** [comment]
期待

**Comment by togiter** [comment]
okex V5是没整合到通用接口里面去吗？ 要调用者独立进行适配吗？

**Comment by nntaoli** [comment]
[goex v2版本](https://github.com/nntaoli-project/goex/blob/v2.0/okx/common/v5.go)
