### ISSUE TITLE
下卖单时对amount进行四舍五入，报account-frozen-balance-insufficient-error(余额不足)的错误

### ISSUE THREAD

**Issue by ts65213** [nntaoli-project/goex#198]
我有 0.005 个tnb，下市价卖单时，火币api返回 account-frozen-balance-insufficient-error（余额不足），
原因是goex把 0.005 四舍五入变成了 0.01，超过了我实际拥有的tnb币的数量。

请问这种情况要如何处理呢，谢谢！

四舍五入的代码在huobi/HuobiPro.go，大约237行，placeOrder()方法里

**Comment by nntaoli** [comment]
这个币估计是火币限制最小下单量0.01吧

**Comment by ts65213** [comment]
囧，其实我下单量是1738.675958...，然后四舍五入成了1738.68
