### ISSUE TITLE
为何我找不到gate的行情接口？

### ISSUE THREAD

**Issue by conbanwa** [nntaoli-project/goex#202]

**Comment by conbanwa** [comment]
<html>
<body>
<h3 id="goex%E5%B7%B2%E6%94%AF%E6%8C%81%E4%BA%A4%E6%98%93%E6%89%80-23" data-line="15" class="code-line" style="margin-top: 0px; font-weight: normal; margin-bottom: 0.2em; position: relative; color: rgb(212, 212, 212); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">goex已支持交易所<span> </span><code style="color: var(--vscode-textPreformat-foreground); font-family: var(--vscode-editor-font-family, &quot;SF Mono&quot;, Monaco, Menlo, Consolas, &quot;Ubuntu Mono&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Courier New&quot;, monospace); font-size: 1em; line-height: 1.357em;">23+</code></h3>

交易所 | 行情接口 | 交易接口 | 版本号
-- | -- | -- | --
huobi.pro | Y | Y | 1
hbdm.com | Y (REST / WS) | Y | 1
okex.com (spot/future) | Y (REST / WS) | Y | 1
okex.com (swap future) | Y | Y | 2
binance.com | Y | Y | 1
kucoin.com | Y | Y | 1
bitstamp.net | Y | Y | 1
bitfinex.com | Y | Y | 1
zb.com | Y | Y | 1
kraken.com | Y | Y | *
poloniex.com | Y | Y | *
big.one | Y | Y | 2\|3
hitbtc.com | Y | Y | *
coinex.com | Y | Y | 1
exx.com | Y | Y | 1
bithumb.com | Y | Y | *
gate.io | Y | N | 1


</body>
</html>

**Comment by nntaoli** [comment]
不好意思，现在版本删除了gateio相关代码
