### ISSUE TITLE
币安合约双向持仓

### ISSUE THREAD

**Issue by wuyushuai** [nntaoli-project/goex#214]
设置双向持仓 下单需要参数  positionSide  否则会下单失败

**Comment by nntaoli** [comment]
期货限价单已双向持仓，主要加入LimitOrderOptionalParameter参数"goex.Futures_Twoway_Position_Mode"：
`LimitFuturesOrder(goex.BTC_USDT, goex.SWAP_USDT_CONTRACT, "12000", "0.01", goex.OPEN_BUY, goex.Futures_Twoway_Position_Mode)`
