### ISSUE TITLE
v2版本需求，建议收集贴

### ISSUE THREAD

**Issue by nntaoli** [nntaoli-project/goex#215]
1. golang版本号: **1.18.6** +
2. 深度数据：买单: 升序；卖单：降序 ，ask[0]表示卖一，bid[0]表示买一

**Comment by pengbotter** [comment]
几个大的主流交易所必须得支持

**Comment by togiter** [comment]
顶顶顶

**Comment by pengbotter** [comment]
已收到，谢谢

**Comment by 0xshandy** [comment]
支持websocket吗

**Comment by nntaoli** [comment]
> 支持websocket吗

目前在考虑做pro版本，为了持续开发动力，pro版本可能会收取一定服务费用

**Comment by togiter** [comment]
建议不要预定义交易对对象，让调用中传参数构建就行了

**Comment by nntaoli** [comment]
> 建议不要预定义交易对对象，让调用中传参数构建就行了

可以自己构建CurrencyPair对象的，支持任何交易对交易的，v1版也是可以自己构建交易对的

**Comment by Roninchen** [comment]
支持websocket吗

**Comment by gzw13999** [comment]
websocket得支持，毕竟各大交易所都在建议用websocket接入。

**Comment by ImAntic** [comment]
> 

pro版本出来了没，求联系

**Comment by nntaoli** [comment]
> > 
> 
> pro版本出来了没，求联系

没pro版本哦

**Comment by brook-w** [comment]
@nntaoli 建议支持 ws 和目前主流的交易所 使用了 v2 版本 币安很多方法都没实现

**Comment by brook-w** [comment]
应该是 币安所有的都没实现

**Comment by nntaoli** [comment]
> 应该是 币安所有的都没实现

币安的实现了部分

**Comment by conbanwa** [comment]
https://github.com/conbanwa/wstrader 这个目前支持 各大交易所的websocket
