### ISSUE TITLE
not found currency pair

### ISSUE THREAD

**Issue by ninki51** [nntaoli-project/goex#224]
> btcUSDTCurrencyPair, err := goexv2.OKx.Spot.NewCurrencyPair(model.BTC, model.USDT)//建议这样构建CurrencyPair
> 	if err != nil {
> 		panic(err)
> 	}

这段代码报错 not found currency pair

**Comment by nntaoli** [comment]
_, _, err := goexv2.OKx.Spot.GetExchangeInfo() //建议调用
	if err != nil {
		panic(err)
	}
	btcUSDTCurrencyPair, err := goexv2.OKx.Spot.NewCurrencyPair(model.BTC, model.USDT)//建议这样构建CurrencyPair
	if err != nil {
		panic(err)
	}
