### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by qmhlan** [nntaoli-project/goex#226]
直接go get导入的是1.3.3版本，我看是2022年的版本了，能否发行一个最新版的，22年的版本比较老的，我看说的v2版本需要用开发版本？

**Comment by qmhlan** [comment]
直接go get v2版本就是最新的代码库？
go get github.com/nntaoli-project/goex/v2

**Comment by nntaoli** [comment]
是的，现在维护的是v2版本,但是支持的交易所比较少

**Comment by nntaoli** [comment]
可以在go.mod里面写： github.com/nntaoli-project/goex/v2 latest
