### ISSUE TITLE
btcbox.co.jp 有没有kline的接口？

### ISSUE THREAD

**Issue by qyvlik** [nntaoli-project/GoEx#35]
btcbox.co.jp 有没有kline的接口？

**Comment by nntaoli** [comment]
https://www.btcbox.co.jp/api/doc/v1#Reference     官网好像没看到

**Comment by qyvlik** [comment]
跟 btcbox 的客服反馈了一下，感觉是有生之年

**Comment by zlq4863947** [comment]
btcbox是个小公司，交易所代码都是从别人那里买的，
你去btcbox主页看看就知道了，他们公司基本没开发人员，因为不需要（🤣）
所以你懂得
