### ISSUE TITLE
Bitfinex adaptTimestamp are invalid

### ISSUE THREAD

**Issue by davidterranova** [nntaoli-project/GoEx#43]
Hi,

It seems that Bitfinex date extraction does not return a valid timestamp (at least regarding the Ticker) :  
`1514294` is missing `10^3` seconds to be the valid date :

Bitfinex Ticker timestamp

Timestamp | Corresponding date | Expected date
------------|---------------------|---------------
1514294 | 18/1/1970  13:38:14 | 26/12/2017  14:13:20
1514294000 | 26/12/2017  14:13:20	| 26/12/2017  14:13:20

Best regards,

**Comment by nntaoli** [comment]
My local test timestamp is normal and returns 1514301340 second.
`
        ticker, _ := bfx.GetTicker(goex.BCH_USD)
	t.Log(ticker.Date)
	tm := time.Unix(int64(ticker.Date),0)
	t.Log(tm)
`
output:
`
bitfinex_test.go:19: 1514301340
bitfinex_test.go:21: 2017-12-26 23:15:40 +0800 CST`

**Comment by davidterranova** [comment]
Ok, I initially played with `binance` API and it returns time in `ms`  
Having some consistency or a time.Time would be nice
