### ISSUE TITLE
Panic on OKCoin GetTicker() with certain currency pairs

### ISSUE THREAD

**Issue by i0n** [nntaoli-project/GoEx#44]
Super weird, not sure why. But this will throw an error:

```
  okcoinAPI := okcoin.New(http.DefaultClient, okcoinAccessKey, okcoinSecretKey)
  result, err := okcoinAPI.GetTicker(goex.BTC_USD)
  if err != nil {
    log.Fatal(err)
  }
fmt.Printf("Close: %v\n", result.Last)
```

`panic: interface conversion: interface {} is nil, not map[string]interface {}
`

If I change the currency pair to BTC_CNY the error goes away.

**Comment by i0n** [comment]
Oops, forgot to mention: go version go1.9.2 darwin/amd64

**Comment by nntaoli** [comment]
@i0n okcoin.New is okcoin.cn ,but okcoin.cn is closed, so you should use okexapi := okcoin.NewOKExSpot(http.DefaultClient, okcoinAccessKey, okcoinSecretKey)

**Comment by i0n** [comment]
Hey! Thanks for replying :-)
I have tried okcoin.NewOKExSpot() and okcoin.NewCOM but both produce the same error as above. Only using the standard .New() okcoin.cn with the BTC_CNY pair gets me a valid return.

**Comment by i0n** [comment]
Tell a lie, the okcoin.NewCOM method seems to be working for me now. Amazing project, thanks so much for sharing. Are you open to pull requests for new exchanges?

**Comment by nntaoli** [comment]
all exchange don't support btc_cny , ltc_cny  or other any pair trade.
welcome you pull request for new exchange or fix bug.
