### ISSUE TITLE
GoEx 如何使用？

### ISSUE THREAD

**Issue by xtuyaowu** [nntaoli-project/GoEx#79]
# command-line-arguments
.\HuobiPro_test.go:34:13: undefined: NewHuoBiProSpot
.\HuobiPro_test.go:61:11: undefined: NewHuoBiProPoint
.\HuobiPro_test.go:63:24: undefined: HBPOINT 
.\websocket_test.go:19:8: undefined: NewWsConn

这个项目改如何使用呢？是我的环境问题？

**Comment by nntaoli** [comment]
请先学习Golang开发相关的知识哦。
