### ISSUE TITLE
火币合约签名失败

### ISSUE THREAD

**Issue by geemo** [nntaoli-project/GoEx#90]
火币合约签名失败

**Comment by nntaoli** [comment]
你检查下你的APIkey是否正确，错误信息可以发出来看下

**Comment by geemo** [comment]
@nntaoli 是正确的，我用了官方提供的 demo 测试完全没问题，goex 校验失败只出现在交易 api，比如挂单这种的。。。

**Comment by nntaoli** [comment]
查询账户呢？我明天测试下 @geemo

**Comment by nntaoli** [comment]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/19357247/55768619-2b608300-5ab0-11e9-9df2-bd33c0cc3ce6.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/19357247/55768690-71b5e200-5ab0-11e9-8e73-a90b09a957e8.png">


我这边测试没任何问题哦
