### ISSUE TITLE
ToFloat64这个方法是不是该这么写

### ISSUE THREAD

**Issue by Ultraman95** [nntaoli-project/GoEx#92]
func ToFloat64(v interface{}) float64 {
	if v == nil {
		return 0.0
	}

	switch v.(type) {
	case float64:
		return v.(float64)
	case string:
		vStr := v.(string)
		vF, err := strconv.ParseFloat(vStr, 64)
		if err == nil {
			return vF
		}else{
			panic("to float64 error.")
		}
	default:
		panic("to float64 error.")
	}
}

**Comment by nntaoli** [comment]
其实这个方法不应该抛出`panic`，这样会引起整个程序的崩溃,你觉得呢？ 
@Ultraman95
